---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true
homebrew_brewfile_dir: "{{ playbook_dir }}"

# make sure pyenv is installed and add default versions
install_pyenv: true
# yadr handles this; don't set up the shell
pyenv_init_shell: false
pyenv_python27_version: "2.7.18"
pyenv_python39_version: "3.9.11"
pyenv_python310_version: "3.10.3"
# Python versions to install. We need 2.x for cqlsh
# until we move to cassandra 4 :(
pyenv_python_versions:
  - "{{ pyenv_python27_version }}"
  - "{{ pyenv_python39_version }}"
  - "{{ pyenv_python310_version }}"

# Set global pyenv version
pyenv_global: "{{ pyenv_python39_version }} system"


# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Maps
  - News
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
dockitems_persist:
  - name: "Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 4
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 5
  - name: "Intellij"
    path: "/Applications/IntelliJ IDEA.app"
    pos: 6
  - name: "WebStorm"
    path: "/Applications/WebStorm.app"
    pos: 7
  - name: "iTerm"
    path: "/Applications/iTerm.app"
    pos: 8
  - name: "zoom"
    path: "/Applications/zoom.us.app"
    pos: 9
  - name: "Slack"
    path: "/Applications/Slack.app"
    pos: 10

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/pdehlke/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.yadr
dotfiles_install_command: "~/.yadr/install.sh"

# These have been moved to the local Brewfile
# homebrew_installed_packages:
#   # - ansible # Installed via Pip.
#   - autoconf
#   - bash-completion
#   - doxygen
#   - gettext
#   - gifsicle
#   - git
#   - github/gh/gh
#   - go
#   - gpg
#   - httpie
#   - iperf
#   - libevent
#   - sqlite
#   - mcrypt
#   - nmap
#   - node
#   - nvm
#   - php
#   - ssh-copy-id
#   - cowsay
#   - readline
#   - openssl
#   - pv
#   - wget
#   - wrk
#   - zsh-history-substring-search

# homebrew_taps:
#   - homebrew/core
#   - homebrew/cask

homebrew_cask_appdir: /Applications
# homebrew_cask_apps:
#   - chromedriver
#   - docker
#   - dropbox
#   - firefox
#   - google-chrome
#   - handbrake
#   - licecap
#   - sequel-ace
#   - slack
#   - sublime-text
#   - transmit

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "A File Icon"
  - "Alignment"
  - "Ansible"
  - "AnsibleSnippets"
  - "ApplySyntax"
  - "ayu"
  - "Babel"
  - "BracketHighlighter"
  - "CForm"
  - "CoffeeAngular Syntax"
  - "Colorsublime"
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "EditorConfig"
  - "EditorConfigSnippets"
  - "FileDiffs"
  - "FileIcons"
  - "Generic Config"
  - "Git"
  - "Git Commit Message Syntax"
  - "GitGutter"
  - "GitHub Flavored Markdown Preview"
  - "GitSavvy"
  - "Indent XML"
  - "Jinja2"
  - "JSON Reindent"
  - "JsonTree"
  - "LiveReload"
  - "Markdown Extended"
  - "Maven"
  - "Monokai Extended"
  - "Monokai JSON+"
  - "Mustache"
  - "Origami"
  - "Package Control"
  - "PackageDev"
  - "Pretty JSON"
  - "Pretty Shell"
  - "Seti_UI"
  - "Seti_UX"
  - "SideBarEnhancements"
  - "SideBarGit"
  - "SJSON"
  - "SSH Config"
  - "SublimeCodeIntel"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "SublimeREPL"
  - "Terrafmt"
  - "Terraform"
  - "TrailingSpaces"
  - "WordCount"
  - "ZSH"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - "tasks/postprovision.yml"

